apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../operators/ircbot-operator/config/default
  - threadrbot_rbac.yaml

images:
  - name: ghcr.io/carverauto/threadr-ircbot-operator
    newName: ghcr.io/carverauto/threadr-ircbot-operator
    newTag: v0.0.11-dev-20260308-3

patches:
  - path: manager_env_patch.yaml
  - path: remove_auth_proxy_patch.yaml
