apiVersion: v1
kind: ConfigMap
metadata:
  name: threadr-control-plane-config
data:
  PHX_HOST: threadr.carverauto.dev
  THREADR_MESSAGING_ENABLED: "false"
  THREADR_BROADWAY_ENABLED: "false"
  THREADR_BOT_STATUS_OBSERVER_ENABLED: "true"
  THREADR_BOT_IMAGE_DRIFT_SYNCER_ENABLED: "true"
  THREADR_EMBEDDINGS_PROVIDER: Threadr.ML.Embeddings.HashProvider
  THREADR_EMBEDDINGS_MODEL: term-hash-384-v1
  THREADR_IRC_BOT_DEFAULT_IMAGE: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:c3ea7adc8d5a25efaa6bbe8b813f8af9564df74eb280ae2fc1da25b72a5e7144
  THREADR_DISCORD_BOT_DEFAULT_IMAGE: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:c3ea7adc8d5a25efaa6bbe8b813f8af9564df74eb280ae2fc1da25b72a5e7144
