apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadr-control-plane
spec:
  template:
    spec:
      initContainers:
        - name: migrate
          $patch: delete
      containers:
        - name: threadr-control-plane
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:f490e194d64cff2486371566389276b09158189f33e2ab42849190324ec706b0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: threadr-bootstrap-operator-admin
spec:
  template:
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:f490e194d64cff2486371566389276b09158189f33e2ab42849190324ec706b0
      containers:
        - name: bootstrap-operator-admin
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:f490e194d64cff2486371566389276b09158189f33e2ab42849190324ec706b0
