apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadr-control-plane
spec:
  template:
    spec:
      initContainers:
        - name: migrate
          $patch: delete
      containers:
        - name: threadr-control-plane
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:6681475226d9be27e0de2bbcf86edcf8f595a973fd1b794d39e5a61866aa9a49
---
apiVersion: batch/v1
kind: Job
metadata:
  name: threadr-bootstrap-operator-admin
spec:
  template:
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:6681475226d9be27e0de2bbcf86edcf8f595a973fd1b794d39e5a61866aa9a49
      containers:
        - name: bootstrap-operator-admin
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:6681475226d9be27e0de2bbcf86edcf8f595a973fd1b794d39e5a61866aa9a49
