apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadr-control-plane
spec:
  template:
    spec:
      initContainers:
        - name: migrate
          $patch: delete
      containers:
        - name: threadr-control-plane
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:2e59277970321c77e29f169da4ffcdeb1353271ed9a003c25784e43a42c3ea0e
---
apiVersion: batch/v1
kind: Job
metadata:
  name: threadr-bootstrap-operator-admin
spec:
  template:
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:2e59277970321c77e29f169da4ffcdeb1353271ed9a003c25784e43a42c3ea0e
      containers:
        - name: bootstrap-operator-admin
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:2e59277970321c77e29f169da4ffcdeb1353271ed9a003c25784e43a42c3ea0e
