apiVersion: v1
kind: ConfigMap
metadata:
  name: threadr-control-plane-config
data:
  PHX_HOST: threadr-control-plane.threadr.svc.cluster.local
  PORT: "4000"
  PHX_SERVER: "true"
  THREADR_BROADWAY_ENABLED: "true"
  THREADR_BOT_STATUS_OBSERVER_ENABLED: "false"
