apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadr-worker
spec:
  template:
    spec:
      initContainers:
        - name: nats-setup
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:391172f172857cb24ae2c697a92b31534c8b692a06c4920ef5a247b1d2bd769f
      containers:
        - name: threadr-worker
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:391172f172857cb24ae2c697a92b31534c8b692a06c4920ef5a247b1d2bd769f
