apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadr-worker
spec:
  template:
    spec:
      initContainers:
        - name: nats-setup
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:47a2c07c85e36d660a6c2565149043ea7fe6088af167441c85161506ef1d570c
      containers:
        - name: threadr-worker
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:47a2c07c85e36d660a6c2565149043ea7fe6088af167441c85161506ef1d570c
