apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadr-worker
spec:
  template:
    spec:
      initContainers:
        - name: nats-setup
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:f830adf0e94528f5d69f034a8ba449738c50ebb87030ebd3be8e3b3af7764cfd
      containers:
        - name: threadr-worker
          image: ghcr.io/carverauto/threadr/threadr-control-plane@sha256:f830adf0e94528f5d69f034a8ba449738c50ebb87030ebd3be8e3b3af7764cfd
