apiVersion: v1
kind: ConfigMap
metadata:
  name: threadr-worker-config
data:
  THREADR_WEB_ENABLED: "false"
  THREADR_MESSAGING_ENABLED: "true"
  THREADR_BROADWAY_ENABLED: "true"
  THREADR_BOT_OPERATION_DISPATCHER_ENABLED: "false"
  THREADR_BOT_STATUS_OBSERVER_ENABLED: "false"
  THREADR_NATS_HOST: nats.threadr.svc.cluster.local
  THREADR_NATS_PORT: "4222"
  THREADR_NATS_TLS: "true"
  THREADR_NATS_TLS_VERIFY: verify_peer
  THREADR_NATS_TLS_SERVER_NAME: nats.threadr.svc.cluster.local
  THREADR_NATS_CA_CERT_FILE: /etc/threadr/nats/ca/tls.crt
  THREADR_NATS_CLIENT_CERT_FILE: /etc/threadr/nats/client/tls.crt
  THREADR_NATS_CLIENT_KEY_FILE: /etc/threadr/nats/client/tls.key
