apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app.kubernetes.io/name: threadr-nats
  ports:
    - name: nats
      port: 4222
      targetPort: 4222
    - name: monitor
      port: 8222
      targetPort: 8222
