FROM --platform=linux/amd64 python:3.11-slim

WORKDIR /app

COPY . /app

# Install any system dependencies required for Python packages
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
&& rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "process_messages.py"]

