FROM --platform=linux/amd64 nvidia/cuda:12.3.2-runtime-ubuntu22.04

WORKDIR /app

COPY . /app

# Install system dependencies required for Python packages
# Including Python3 pip
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    python3-dev \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Use pip3 to install Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["python3", "create_embeddings.py"]

